apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: publish-buffer-data
  namespace: cloudflow
  labels:
    strimzi.io/cluster: cloudflow
spec:
  partitions: 50
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824